quality of life updates

diff --git a/LepWrap b/LepWrap
--- a/LepWrap
+++ b/LepWrap
@@ -11,19 +11,27 @@ else
   exit 1
 fi
 
-if [ ! -f config.yaml ]; then
-  echo -e "ERROR:\nThe file 'config.yaml' is required to run LepWrap, but not found in the current directory. Creating one."
-  cat <<EOF >config.yml
+if [[ -z "$2" ]]; then
+    if [ ! -f config.yml ]; then
+      echo -n "Error: "
+      printf "\033[01;32m"
+      printf "config.yml"
+      printf "\033[0m"
+      echo " not found"
+      echo "The file 'config.yml' was created for you, please edit it and run LepWrap again"
+    cat <<EOF >config.yml
 # Configuration file for LepWrap
 #########################################################
 #                       Lep-Map 3                       #
 #########################################################
+# change this to false if you want to skip Lep-Map3
+run_lepmap: true
 
 #---------------#
 #  ParentCall2  #
 #---------------#
 # the filtered VCF file with your genotype likelihoods:
-vcf: "out.15.missrecode90.vcf"
+vcf: "mydata.vcf"
 
 # Instructions to create pedigree file: https://sourceforge.net/p/lep-map3/wiki/software/LepMap3 Home/#parentcall2
 # the pedigree file associated with your data
@@ -126,30 +134,29 @@ distance_method: "useKosambi=1"
 #                       Lep-Anchor                      #
 #########################################################
 
-# change this to true if you also want to run Lep-Anchor
+# change this to false if you want to skip Lep-Anchor
 run_lepanchor: true
 
 # the path to the genome assembly you are trying to anchor
 # ideally it is *not* gzipped and ends in .fa, but there are built-in workarounds if it is. 
-assembly: "YFT.genome.latest.fasta"
+assembly: "assembly.fasta"
 
 # the number of linkage groups you have
 lg_count: 24
 
 # if you have a PAF file of long reads mapped to your genome, add it here, otherwise leave the text as "/dev/null"
-PAF_file: "alnPB.paf"
+PAF_file: "/dev/null"
 
 # if you have a proximity file add it here, otherwise leave the text as "/dev/null".
 # This isn't yet implemented in Lep-Anchor, so don't change this.
 proximity_file: "/dev/null"
 
-# Which system is appropriate for running the HaploMerger2 section? Comment out the one that doesn't apply.
-# This is kinda necessary for the correct lastz binaries. If you have a Debian or Arch based system, Ubuntu
-# should work (tested for Arch Linux, at least). If using a Fedora/RedHat based system, try the CentOS options.
-# If you aren't sure, try "Ubuntu" and see what happens! I'm not actually convinced it matters, but you never know.
-OS_info: "Ubuntu"
-#OS_info: "CentOS5"
-#OS_info: "CentOS6"
+# Which system is appropriate for running the HaploMerger2 section? Keep one and comment out the others.
+# This is kinda necessary for the lastz binaries. The ubuntu binaries seem to work on Debian/Ubuntu/Arch/CentOS,
+# but feel free to play it safe and use centOS* for any RedHat/Fedora based systems.
+OS_info: "ubuntu"
+#OS_info: "centOS5"
+#OS_info: "centOS6"
 
 
 #------------#
@@ -179,7 +186,6 @@ lepanchor_input: "noIntervals=1"  # uses map position input
 haplotype_limit: 5000
 
 # If there are any additional parameters you would like to use for PlaceAndOrientContigs (e.g. randomOrder=1), add them here
-
 extra_params_PlaceOrient: "keepEmptyIntervals=1 numRuns=10"
 
 
@@ -198,32 +204,63 @@ LA_edge_length: 20
 LA_trim_cutoff: 5
 EOF
   exit 1
+  fi
+    CONF=config.yml
+else
+    if [ ! -f $2 ]; then
+      echo -n "Error: Config file "
+      printf "\033[01;32m"
+      printf "$2"
+      printf "\033[0m"
+      echo " not found"
+      exit 1
+    else
+      CONF=$2
+    fi
 fi
 
 if [[ -z "$1" ]]; then
-  echo "Perform the modules of Lep-Map3 and optionally Lep-Anchor" 
-  echo "Make sure config.yaml is properly configured for how you intend to run things."
+  echo "Perform the modules of Lep-Map3 and/or Lep-Anchor" 
+  echo "Make sure the config file (default: config.yml) is properly configured for how you want to run things"
+  echo "The second positional argument is optional if your config file is named config.yml"
   echo ""
-  echo "[usage] LepWrap <number of threads to use>"
-  echo "[example] LepWrap 16" 
+  echo "[usage]   LepWrap <# of threads> <config.yml>"
+  echo "[example] LepWrap 16"
+  echo "[example] LepWrap 30 kosambi.20iterations.yml"
   exit 1
 fi
 
 lepmap(){
   echo "Running Lep-Map3"
   sleep 2s
-  snakemake --cores $1 --snakefile ./rules/LepMap3/LepMap3.smk --directory .
+  snakemake --cores $1 --snakefile ./rules/LepMap3/LepMap3.smk --configfile $CONF --directory .
 }
 
 lepanchor(){
-  LA=$(grep "run_lepanchor" config.yaml | cut -d":" -f2 | xargs | tr '[:upper:]' '[:lower:]')
-  if [ $LA == "true" ]; then
-    echo -e "\nRunning Lep-Anchor"
-    sleep 2s
-    snakemake --cores $1 --snakefile ./rules/LepAnchor/LepAnchor.smk --directory .
-  else
-    exit 1
-  fi
+  echo -e "\nRunning Lep-Anchor"
+  sleep 2s
+  snakemake --cores $1 --snakefile ./rules/LepAnchor/LepAnchor.smk --configfile $CONF --directory .
 }
 
-lepmap $1 && lepanchor $1
+# copy lastz binaries into conda path if they aren't already there
+OSname=$(grep "^OS_info" config.yml | cut -d":" -f2 | xargs | tr '[:upper:]' '[:lower:]')
+if [ -z "$CONDA_PREFIX" ]; then
+  echo "No active conda environment detected"
+else
+  cp -n software/LepAnchor/deps/$OSname/* $CONDA_PREFIX/bin
+fi
+
+LM=$(grep "run_lepmap" config.yml | cut -d":" -f2 | xargs | tr '[:upper:]' '[:lower:]')
+LA=$(grep "run_lepanchor" config.yml | cut -d":" -f2 | xargs | tr '[:upper:]' '[:lower:]')
+
+if [ $LM == "true" ]; then
+  lepmap $1 $CONF
+else
+  echo "Skipping Lep-Map3"
+fi
+
+if [ $LA == "true" ]; then
+  lepanchor $1 $CONF
+else
+  echo "Skipping LepAnchor"
+fi
