Update lepmap2anchor

diff --git a/scripts/lepmap2anchor b/scripts/lepmap2anchor
--- a/scripts/lepmap2anchor
+++ b/scripts/lepmap2anchor
@@ -1,12 +1,28 @@
 #! /usr/bin/env bash
 
-LG=$(ls *.intervals | wc -l)
+if [[ -z "$1" ]]; then
+cat <<EOF
 
-if [ ! -f $1 ]; then
-echo "error: marker file $(echo $1) not found"
-exit 1
+Convert Lep-Map3 interval files into a single Lep-Anchor input file.
+
+[usage]:	lepmap2anchor <marker_file>
+[example]: 	scripts/lepmap2anchor snps.txt
+
+EOF
+  exit 1
 fi
 
+LG=$(ls intervals/*.intervals | wc -l)
+
+if [ ! -f $1 ]; then
+    echo "Error: marker file $(echo $1) not found. It may be generated using scripts/extract_markers.sh"
+    exit 1
+fi
+
+echo "Identified $LG interval files in intervals/ directory"
+
 for i in $(seq 1 $LG); do
-    awk -vn=$i '(NR==FNR){map[NR-1]=$0}(NR!=FNR){$1=map[$1] "\t" n;print}' $1 ordered.$i.intervals >> lepmap3_map.la
+    awk -vn=$i '(NR==FNR){map[NR-1]=$0}(NR!=FNR){$1=map[$1] "\t" n;print}' $1 intervals/ordered.$i.intervals >> lepmap3_intervals.la
 done
+
+echo "Created Lep-Anchor input file lepmap3_intervals.la"
